# Default group vars for all Windows hosts
ansible_user: Administrator
ansible_password: 
ansible_connection: winrm
ansible_port: 5986
ansible_winrm_scheme: https
ansible_winrm_server_cert_validation: ignore

# If using basic auth over HTTP (not recommended for prod):
# ansible_port: 5985
# ansible_winrm_scheme: http
# ansible_winrm_transport: ntlm
