[windows]
# Replace with your Windows VM private IPs or DNS names
# vm1 ansible_host=10.0.0.4
# vm2 ansible_host=10.0.0.5

[windows:vars]
ansible_user=Administrator
ansible_password=
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_scheme=https
