---
- name: Windows VM maintenance playbook
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Test WinRM connectivity
      win_ping:

    # - name: Ensure chocolatey is installed
    #   win_chocolatey:
    #     name: chocolatey
    #     state: present
    #   register: choco

    # - name: Install latest 7zip (example package)
    #   win_chocolatey:
    #     name: 7zip
    #     state: latest
    #   when: choco.changed or true

    - name: Create C:\\temp directory
      win_file:
        path: C:\\temp
        state: directory

    - name: Copy installer script
      win_copy:
        dest: C:\\temp\\install_appliance.ps1
        src: ../../scripts/install_appliance.ps1

    - name: Run installer script
      win_shell: C:\\temp\\install_appliance.ps1
      register: run_appliance_install

    - name: Print script output
      debug:
        var: run_appliance_install.stdout
